name: Pawpet API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pawpet-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: pawpet-api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Linting
        run: npm run ci:lint

      - name: Type Checking
        run: npm run typecheck
